hadd /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/nominal/TopAnalysis_TTJets-madgraph_Fall08_all_all.root /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/TopAnalysis_TTJets-madgraph_Fall08_all_00*.root
hadd /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/nominal/TopAnalysis_WJets_madgraph_Fall08_all.root /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/TopAnalysis_WJets_madgraph_Fall08_00*.root
hadd /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/nominal/TopAnalysis_ZJets_madgraph_Fall08_all.root /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/TopAnalysis_ZJets_madgraph_Fall08_00*.root
hadd /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/nominal/TopAnalysis_InclusiveMuPt15_Summer08_all.root /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/TopAnalysis_InclusiveMuPt15_Summer08_00*.root
hadd /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/nominal/TopAnalysis_ST_s.root /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/TopAnalysis_ST_s_00*.root
hadd /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/nominal/TopAnalysis_ST_t.root /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/TopAnalysis_ST_t_00*.root
hadd /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/nominal/TopAnalysis_ST_tW.root /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/TopAnalysis_ST_tW_00*.root
hadd /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/nominal/TopAnalysis_TauolaTTbar.root /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/TopAnalysis_TauolaTTbar_00*.root
hadd /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/nominal/TopAnalysis_VVJets.root /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/TopAnalysis_VVJets_00*.root
hadd /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/nominal/TopAnalysis_WcJets.root /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/TopAnalysis_WcJets_Fall08_00*.root


python ~/work/CMSSW_2_2_6/src/TopWork/scripts/counter.py /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/ TopAnalysis_TTJets-madgraph_Fall08_all_ /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/nominal/TopAnalysis_TTJets-madgraph_Fall08_all_all.root off
python ~/work/CMSSW_2_2_6/src/TopWork/scripts/counter.py /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/ TopAnalysis_WJets_madgraph_Fall08_ /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/nominal/TopAnalysis_WJets_madgraph_Fall08_all.root off
python ~/work/CMSSW_2_2_6/src/TopWork/scripts/counter.py /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/ TopAnalysis_ZJets_madgraph_Fall08_ /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/nominal/TopAnalysis_ZJets_madgraph_Fall08_all.root
python ~/work/CMSSW_2_2_6/src/TopWork/scripts/counter.py /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/ TopAnalysis_InclusiveMuPt15_Summer08_ /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/nominal/TopAnalysis_InclusiveMuPt15_Summer08_all.root
python ~/work/CMSSW_2_2_6/src/TopWork/scripts/counter.py /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/ TopAnalysis_ST_s_ /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/nominal/TopAnalysis_ST_s.root
python ~/work/CMSSW_2_2_6/src/TopWork/scripts/counter.py /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/ TopAnalysis_ST_t_ /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/nominal/TopAnalysis_ST_t.root
python ~/work/CMSSW_2_2_6/src/TopWork/scripts/counter.py /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/ TopAnalysis_ST_tW_ /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/nominal/TopAnalysis_ST_tW.root
python ~/work/CMSSW_2_2_6/src/TopWork/scripts/counter.py /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/ TopAnalysis_TauolaTTbar_ /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/nominal/TopAnalysis_TauolaTTbar.root
python ~/work/CMSSW_2_2_6/src/TopWork/scripts/counter.py /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/ TopAnalysis_VVJets_ /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/nominal/TopAnalysis_VVJets.root
python ~/work/CMSSW_2_2_6/src/TopWork/scripts/counter.py /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/ TopAnalysis_WcJets_Fall08_ /uscmst1b_scratch/lpc1/cmsroc/yumiceva/TQAF/CMSSW_2_2_6/LowMass_analysis_lyon/nominal/TopAnalysis_WcJets.root
